# Concouse CI Pipeline definition for Spring Boot

resources:
- name: java-docker-image
  type: docker-image
  source:
    repository: java
    tag:        8-jdk

- name: base-docker-build
  type: git
  source:
    uri:    https://github.com/philwebb/spring-boot-concourse.git
    branch: {{branch}}
    paths:
    - ci/docker-builds/base/*

- name: ci-docker-build
  type: git
  source:
    uri:    https://github.com/philwebb/spring-boot-concourse.git
    branch: {{branch}}
    paths:
    - ci/docker-builds/ci/*

- name: base-docker-image
  type: docker-image
  source:
    repository: springboot/ci-base-{{branch}}
    email:      {{docker-email}}
    username:   {{docker-username}}
    password:   {{docker-password}}

- name: ci-docker-image
  type: docker-image
  source:
    repository: springboot/ci--{{branch}}
    email:      {{docker-email}}
    username:   {{docker-username}}
    password:   {{docker-password}}

jobs:
- name: docker-image
  plan:
  - aggregate:
    - get: docker-image
      trigger: true
    - get: java-8-jdk
      trigger: true
  - put: spring-boot-ci
    params:
      build: docker-image/ci/docker-image
